name: Geri Skenderi
description: Personal website
menu:
 - page: Papers
   url: /papers
 - page: Research
   url: /research
   #links:
   # - title: "Project One"
   #   url: "#project-one"
   # - title: "Project Two"
   #   url: "#project-two"
   # - title: "Project Three"
   #   url: "#project-three"
   # - title: "Project Four"
   #   url: "#project-four"
 - page: Curriculum Vitae
   url: /cv
 - page: Teaching
   url: /teaching
menu_external:
 - title: E-mail
   url: "mailto:geri.skenderi@univr.it"
 - title: Twitter
   url: "https://twitter.com/geriskenderi"
 - title: LinkedIn
   url: "https://www.linkedin.com/in/geriskenderi/"
 - title: Github
   url: "https://github.com/geriskenderi"

mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: /
locale: en_GB